[package]
name = "bot"
version = "3.0.0"
authors = ["Woomy4680-exe <matzar1808@gmail.com>"]
edition = "2018"

[dependencies]
serenity = "0.10.5"
tokio = { features = ["full"], version = "1.4.0" }

[profile.release]
lto = true
