[package]
name = "bot"
version = "3.0.0"
authors = ["FII developpement team"]
edition = "2018"

[dependencies]
serenity = "0.10.8"
tokio = { features = ["full"], version = "1.7.0" }

[profile.release]
lto = true
