version: "3"
networks:
  bot:
    external: false
services:
  database:
    image: "postgres:alpine"
    env_file:
      - database.env # configure postgres
    volumes:
      - "./compose-multi-db:/docker-entrypoint-initdb.d"
      - "./data:/var/lib/postgresql/data/"
      - "./:/app/bot"
    networks:
      - bot
  bot:
    build: .
    networks: 
      - "bot"
    environment:
      - DB_HOST=database
    depends_on:
      - database